workflows:
  expo-android:
    name: Expo Android Build

    max_build_duration: 60

    environment:
      node: 18
      groups:
        - expo

    scripts:
      - npm install
      - npm install -g eas-cli
      - eas build -p android --non-interactive --profile preview

    artifacts:
      - '*.apk'
      - '*.aab'
