workflows:
  expo-android:
    name: Expo Android Build

    environment:
      node: latest

    scripts:
      - YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
      - npx expo export

    artifacts:
      - dist/**
